config/routes.rb
Rails.application.routes.draw do


	resources :schools, path: nil do
		resources :departments
		resources :ru_classes
		resources :ru_professors
	end

	get 'about/index'

	root :to => "welcome#index"
	devise_for :users
	resources :users

	resources :departments

	resources :ru_professors do
		resources :prof_comments, shallow: true
	end
	resources :prof_comments

	resources :ru_classes do
		resources :class_comments, shallow: true
	end
	resources :class_comments

end

app/models/class_comment.rb
class ClassComment < ActiveRecord::Base
  belongs_to :ru_class
  belongs_to :user
end

app/models/department.rb
class Department < ActiveRecord::Base
  include FriendlyId
  friendly_id :name

  belongs_to :school

  validates :name, :description, presence: true

  has_many :ru_classes
  has_many :ru_professors
end

app/models/prof_class_map.rb
class ProfClassMap < ActiveRecord::Base
  belongs_to :ru_professor
  belongs_to :ru_class
end

app/models/prof_comment.rb
class ProfComment < ActiveRecord::Base
  belongs_to :ru_professor
  belongs_to :user
end

app/models/ru_class.rb
class RuClass < ActiveRecord::Base
  include FriendlyId
  friendly_id :class_title
  validates :class_title, :class_synopsis, presence: true, uniqueness: true

  has_many :class_comments
  has_many :prof_class_maps
  has_many :ru_professors, :through => :prof_class_maps

  belongs_to :department
end

app/models/ru_professor.rb
class RuProfessor < ActiveRecord::Base
  include FriendlyId
  friendly_id :last_name
  validates :first_name, :last_name, :email, presence: true

  has_many :prof_comments
  has_many :prof_class_maps
  has_many :ru_classes, :through => :prof_class_maps

  belongs_to :department
end

app/models/school.rb
class School < ActiveRecord::Base
  include FriendlyId
  friendly_id :name
  validates :name, :summary, :website, :address, presence: true

  has_many :departments

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :prof_comments
  has_many :class_comments
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/ru_classes_controller.rb
class RuClassesController < ApplicationController
  def index
    @classes = RuClass.order("class_title").page(params[:page]).per(10)
  end

  def show
    @class = RuClass.friendly.find(params[:id])
    @class_comment =ClassComment.new
    @comments = @class.class_comments.order('updated_at DESC')
    @professors = @class.ru_professors
    @department = @class.department

  end

  def create
    @class = RuClass.new(class_params)
    @class.department =Department.find(params[:ru_class][:department_select])

    if params[:ru_class][:ru_class_select].nil?
      puts "I'll probably put a pop-up here to see if they want to add one."
    else

      STDOUT.puts "IM INSIDE"
      prof_id=params[:ru_class][:ru_professor_select]
      prof_id.shift
      prof_id.each { |x|
        @profClassMap = ProfClassMap.new

        @prof=RuProfessor.find(x)

        @profClassMap.ru_class=@class
        @profClassMap.ru_professor=@prof
        @profClassMap.save

      }

    end


    if @class.save
      redirect_to @class
    else
      render 'new'
    end
  end

  def new
    @class = RuClass.new
  end

  def edit
    @class = RuClass.friendly.find(params[:id])
  end

  def update
    @class = RuClass.friendly.find(params[:id])
    if @class.update(class_params)
      redirect_to @class
    else
      redirect_to edit_ru_class_path
    end
  end
  private
  def class_params
    params.require(:ru_class).permit(:class_title, :class_code, :class_synopsis)
  end
end

app/controllers/ru_professors_controller.rb
class RuProfessorsController < ApplicationController
  def index
    @professors = RuProfessor.order("last_name").page(params[:page]).per(10)
  end

  def show
    @professor = RuProfessor.friendly.find(params[:id])

    @prof_comment =ProfComment.new
    @comments = @professor.prof_comments.order('updated_at DESC')
    @classes=@professor.ru_classes
    @department=@professor.department

  end

  def create
    @professor = RuProfessor.new(prof_params)

    if (params[:ru_professor][:department_select]).nil?
      puts 'Pop-up for department creation'
    else
      @professor.department =Department.find(params[:ru_professor][:department_select])
    end

    if (params[:ru_professor][:ru_class_select]).nil?
      puts 'Pop-up for class creation'
    else
      class_id=params[:ru_professor][:ru_class_select]
      class_id.shift
      class_id.each { |x|
        @profClassMap = ProfClassMap.new

        @class=RuClass.find(x)

        @profClassMap.ru_class=@class
        @profClassMap.ru_professor=@professor
        @profClassMap.save

      }
    end

    if @professor.save
      redirect_to @professor
    else
      render 'new'
    end
  end

  def new
    @professor = RuProfessor.new
  end

  def edit
    @professor = RuProfessor.friendly.find(params[:id])
    @fullname= @professor.first_name + " " + @professor.last_name
  end

  def update
    @professor = RuProfessor.friendly.find(params[:id])
    if @professor.update(prof_params)
      redirect_to @professor
    else
      redirect_to edit_school_path
    end
  end

  private
  def prof_params
    params.require(:ru_professor).permit(:first_name, :last_name, :email, :department)
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def new
    @school = School.new
  end

  def create
    @school = School.new(school_params)


    if @school.save
      redirect_to @school
    else
      render 'new'
    end
  end

  def index
    @schools = School.order("name").page(params[:page]).per(10)
  end

  def show
    @school = School.friendly.find(params[:id])
  end

  def edit
    @school = School.friendly.find(params[:id])
  end

  def update
    @school = School.friendly.find(params[:id])
    if @school.update(school_params)
      redirect_to @school
    else
      redirect_to edit_school_path
    end
  end


  private
  def school_params
    params.require(:school).permit(:name, :summary, :website, :address, :phone)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @prof_comments = @user.prof_comments.all.page(params[:page]).per(10)
    @class_comments = @user.class_comments.all.page(params[:page]).per(10)


    #I want user to people to view the 'profiles' of the
    #
    #    unless @user == current_user
    #      redirect_to :back, :alert => "Access denied."
    #    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/class_comments_helper.rb
module ClassCommentsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/prof_comments_helper.rb
module ProfCommentsHelper
end

app/helpers/ru_classes_helper.rb
module RuClassesHelper
end

app/helpers/ru_professors_helper.rb
module RuProfessorsHelper
end

app/helpers/school_helper.rb
module SchoolHelper
end

app/views/ru_professors/create.html.erb
<h1>Professor#create</h1>
<p>Find me in app/views/professor/create.html.erb</p>

app/views/ru_professors/edit.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="jumbotron">
        <h1>
          Edit Information for <%= @fullname %>
        </h1>



        <%= form_for @professor, url: ru_professor_path(@professor), :html => {:class => "form-horizontal"} do |p| %>
            <% if @professor.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@professor.errors.count, "error") %> prohibited
                    this professor from being saved:</h2>
                  <ul>
                    <% @professor.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>

            <fieldset>

              <!-- Form Name -->
              <legend>Edit Professor</legend>

              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="prof_name">Professor Name</label>

                <div class="col-md-4">
                  <%= p.text_field :first_name, class: "form-control input-md", placeholder: "First Name" %>
                </div>

                <div class="col-md-4">
                  <%= p.text_field :last_name, class: "form-control input-md", placeholder: "Last Name" %>
                </div>
              </div>

              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="prof_email">Professor Email</label>

                <div class="col-md-4">
                  <%= p.email_field :email, class: "form-control input-md", placeholder: "Email Address" %>

                </div>
              </div>

              <!-- Button -->
              <div class="form-group">
                <label class="col-md-4 control-label" for="submit"></label>

                <div class="col-md-4">

                  <%= p.submit "Save Professor", class: "btn btn-default" %>

                </div>
              </div>

            </fieldset>
        <% end %>


      </div>
    </div>
  </div>
  <div class="row clearfix">

  </div>
</div>

app/views/ru_professors/index.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="jumbotron">
        <h1>
          The Professors Will Go Here!
        </h1>

        <p>
          Blahdy Lorem Ipsum

        </p>

        <p>
          <%= link_to "Add New Professor", {:controller => "ru_professors", action: "new"}, class: "btn btn-primary btn-large" %>
        </p>
      </div>
      <div class="row clearfix">

        <div style="display: block"><%= paginate @professors %></div>

        <% @professors.each do |p| %>
            <div class="col-md-4 column">


              <div class="panel panel-default">
                <div class="panel-heading">
                  <h3 class="panel-title">
                    <%= link_to p.first_name + " "+p.last_name, p %>
                  </h3>
                </div>
                <div class="panel-body">
                  <%= mail_to p.email %>
                  </br>
                </div>
              </div>


            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/ru_professors/new.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="jumbotron">
        <h1>
          Add a Professor!
        </h1>



        <%= form_for :ru_professor, url: ru_professors_path, :html => {:class => "form-horizontal"} do |p| %>
            <% if @professor.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@professor.errors.count, "error") %> prohibited
                    this professor from being saved:</h2>
                  <ul>
                    <% @professor.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>

            <fieldset>

              <!-- Form Name -->
              <legend>Create Professor</legend>

              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="prof_name">Professor Name</label>

                <div class="col-md-4">
                  <%= p.text_field :first_name, class: "form-control input-md", placeholder: "First Name" %>
                </div>

                <div class="col-md-4">
                  <%= p.text_field :last_name, class: "form-control input-md", placeholder: "Last Name" %>
                </div>
              </div>

              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="prof_email">Professor Email</label>

                <div class="col-md-4">
                  <%= p.email_field :email, class: "form-control input-md", placeholder: "Email Address" %>

                </div>
              </div>

              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="prof_department">Professor Department</label>

                <div class="col-md-4">
                  <%= p.select :department_select, options_for_select(Department.all.map { |dpt| [dpt.name, dpt.id] }), {}, {:class => "chosen-select"} %>
                </div>
              </div>

              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="prof_department">Choose Classes</label>

                <div class="col-md-4">
                  <%= p.select :ru_class_select, options_for_select(RuClass.all.map { |r| [r.class_title, r.id] }), {}, {:multiple => true, :class => "chosen-select"} %>
                </div>
              </div>


              <!-- Button -->
              <div class="form-group">
                <label class="col-md-4 control-label" for="submit"></label>

                <div class="col-md-4">

                  <%= p.submit "Add Professor", class: "btn btn-default" %>

                </div>
              </div>

            </fieldset>
        <% end %>


      </div>
    </div>
  </div>
  <div class="row clearfix">

  </div>
</div>

app/views/ru_professors/show.html.erb
<div class="container">
  <div class="row clearfix">
    <div style="float: left">
      <div class="jumbotron">
        <h1>
          <%= @professor.first_name + " " +@professor.last_name %>
        </h1>


        <h3><%= mail_to @professor.email %></h3>

        <h3>Classes</h3>

        <% if @classes.size == 0 %>
            <p><%= t('professorNoClasses') %> <%= render 'layouts/links/addClassLinker' %>
            </p>
        <% else %>

            <% @classes.each do |c| %>


                <%= link_to c.class_title, c %> |

            <% end %>
        <% end %>
        <h3>Department</h3>
        <% if @department.nil? %>
            <p><%= t('professorNoDepartment') %> <%= render 'layouts/links/addDepartmentLinker' %>
            </p>
        <% else %>

            <%= link_to @department.name, @department %>
        <% end %>


      </div>
    </div>
    <div style="float: right">
      <div class="jumbotron">
        <div class="ratingsbox"></div>
        <h2>Ratings</h2>
        A rating system using stars will go here.

      </div>


    </div>

  </div>
  <div class="commentForm">


    <div class="panel panel-default">
      <div class="panel-body">
        <% if user_signed_in? %>
            <button type="button" class="btn btn-primary commentToggle" data-toggle="collapse" data-target="#commentFormHolder">
              Add Comment
            </button>

            <div id="commentFormHolder" class="collapse out"><%= render 'layouts/comments/add_prof_comment' %></div>
        <% else %>
            <%= render 'layouts/please_sign_in' %>
        <% end %>
      </div>
    </div>

  </div>

  <div class="row clearfix">


    <div id="commentContainer">
      <h2>Comments</h2>
      <% @comments.each do |c| %>
          <div class="col-md-4 column">


            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">
                  <%= link_to c.user.name, current_user %>
                </h3>
              </div>
              <div class="panel-body">
                <%= c.body %>
              </div>
            </div>


          </div>
      <% end %>
    </div>

  </div>
</div>