config/routes.rb
Rails.application.routes.draw do


	resources :schools, path: nil do
		resources :departments
		resources :ru_classes
		resources :ru_professors
	end

	get 'about/index'

	root :to => "welcome#index"
	devise_for :users
	resources :users

	resources :departments

	resources :ru_professors do
		resources :prof_comments, shallow: true
	end
	resources :prof_comments

	resources :ru_classes do
		resources :class_comments, shallow: true
	end
	resources :class_comments

end

app/models/class_comment.rb
class ClassComment < ActiveRecord::Base
  belongs_to :ru_class
  belongs_to :user
end

app/models/department.rb
class Department < ActiveRecord::Base
  include FriendlyId
  friendly_id :name

  belongs_to :school

  validates :name, :description, presence: true

  has_many :ru_classes
  has_many :ru_professors
end

app/models/prof_class_map.rb
class ProfClassMap < ActiveRecord::Base
  belongs_to :ru_professor
  belongs_to :ru_class
end

app/models/prof_comment.rb
class ProfComment < ActiveRecord::Base
  belongs_to :ru_professor
  belongs_to :user
end

app/models/ru_class.rb
class RuClass < ActiveRecord::Base
  include FriendlyId
  friendly_id :class_title
  validates :class_title, :class_synopsis, presence: true, uniqueness: true

  has_many :class_comments
  has_many :prof_class_maps
  has_many :ru_professors, :through => :prof_class_maps

  belongs_to :department
end

app/models/ru_professor.rb
class RuProfessor < ActiveRecord::Base
  include FriendlyId
  friendly_id :last_name
  validates :first_name, :last_name, :email, presence: true

  has_many :prof_comments
  has_many :prof_class_maps
  has_many :ru_classes, :through => :prof_class_maps

  belongs_to :department
end

app/models/school.rb
class School < ActiveRecord::Base
  include FriendlyId
  friendly_id :name
  validates :name, :summary, :website, :address, presence: true

  has_many :departments

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :prof_comments
  has_many :class_comments
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  def index
    @departments = Department.order("name").page(params[:page]).per(10)
  end

  def show
    @department = Department.friendly.find(params[:id])
    @classlist= @department.ru_classes
    @proflist = @department.ru_professors
  end

  def create
    @department = Department.new(department_params)
    @school = School.find_by_name(params[:school_id])

    @department.school =@school

    if @department.save
      redirect_to @department
    else
      render 'new'
    end
  end

  def new
    @department = Department.new
  end

  def edit
  end

  private
  def department_params
    params.require(:department).permit(:name, :description, :location)
  end
end

app/controllers/ru_classes_controller.rb
class RuClassesController < ApplicationController
  def index
    @classes = RuClass.order("class_title").page(params[:page]).per(10)
  end

  def show
    @class = RuClass.friendly.find(params[:id])
    @class_comment =ClassComment.new
    @comments = @class.class_comments.order('updated_at DESC')
    @professors = @class.ru_professors
    @department = @class.department

  end

  def create
    @class = RuClass.new(class_params)
    @class.department =Department.find(params[:ru_class][:department_select])

    if params[:ru_class][:ru_class_select].nil?
      puts "I'll probably put a pop-up here to see if they want to add one."
    else

      STDOUT.puts "IM INSIDE"
      prof_id=params[:ru_class][:ru_professor_select]
      prof_id.shift
      prof_id.each { |x|
        @profClassMap = ProfClassMap.new

        @prof=RuProfessor.find(x)

        @profClassMap.ru_class=@class
        @profClassMap.ru_professor=@prof
        @profClassMap.save

      }

    end


    if @class.save
      redirect_to @class
    else
      render 'new'
    end
  end

  def new
    @class = RuClass.new
  end

  def edit
    @class = RuClass.friendly.find(params[:id])
  end

  def update
    @class = RuClass.friendly.find(params[:id])
    if @class.update(class_params)
      redirect_to @class
    else
      redirect_to edit_ru_class_path
    end
  end
  private
  def class_params
    params.require(:ru_class).permit(:class_title, :class_code, :class_synopsis)
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def new
    @school = School.new
  end

  def create
    @school = School.new(school_params)


    if @school.save
      redirect_to @school
    else
      render 'new'
    end
  end

  def index
    @schools = School.order("name").page(params[:page]).per(10)
  end

  def show
    @school = School.friendly.find(params[:id])
  end

  def edit
    @school = School.friendly.find(params[:id])
  end

  def update
    @school = School.friendly.find(params[:id])
    if @school.update(school_params)
      redirect_to @school
    else
      redirect_to edit_school_path
    end
  end


  private
  def school_params
    params.require(:school).permit(:name, :summary, :website, :address, :phone)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @prof_comments = @user.prof_comments.all.page(params[:page]).per(10)
    @class_comments = @user.class_comments.all.page(params[:page]).per(10)


    #I want user to people to view the 'profiles' of the
    #
    #    unless @user == current_user
    #      redirect_to :back, :alert => "Access denied."
    #    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/class_comments_helper.rb
module ClassCommentsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/prof_comments_helper.rb
module ProfCommentsHelper
end

app/helpers/ru_classes_helper.rb
module RuClassesHelper
end

app/helpers/ru_professors_helper.rb
module RuProfessorsHelper
end

app/helpers/school_helper.rb
module SchoolHelper
end

app/views/departments/create.html.erb
<h1>Departments#create</h1>
<p>Find me in app/views/departments/create.html.erb</p>

app/views/departments/edit.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="jumbotron">
        <h1>
          Edit Information for <%= @department.name %>
        </h1>



        <%= form_for @department, url: department_path(@department), :html => {:class => "form-horizontal"} do |p| %>
            <% if @department.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@department.errors.count, "error") %> prohibited
                    this class from being saved:</h2>
                  <ul>
                    <% @department.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>

            <fieldset>

              <!-- Form Name -->
              <legend>Edit Department</legend>

              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="prof_name">Department Name</label>

                <div class="col-md-4">
                  <%= p.text_field :name, class: "form-control input-md", placeholder: "Department Name" %>
                </div>

              </div>


              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="prof_department">Department Description</label>

                <div class="col-md-4">
                  <%= p.text_field :description, class: "form-control input-md", placeholder: "Description of the department" %>

                </div>
              </div>

              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="prof_department">Department Location</label>

                <div class="col-md-4">
                  <%= p.text_field :location, class: "form-control input-md", placeholder: "Location of the department" %>

                </div>
              </div>


              <!-- Button -->
              <div class="form-group">
                <label class="col-md-4 control-label" for="submit"></label>

                <div class="col-md-4">

                  <%= p.submit "Save Department", class: "btn btn-default" %>

                </div>
              </div>

            </fieldset>
        <% end %>


      </div>
    </div>
  </div>
  <div class="row clearfix">

  </div>
</div>

app/views/departments/index.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="jumbotron">
        <h1>
          The Departments will go here!
        </h1>

        <p>
          This will be the home page for the departments. </p>

        <p>
          <%= link_to "Add New Department", {:controller => "departments", action: "new"}, class: "btn btn-primary btn-large" %>
        </p>
      </div>
    </div>
  </div>
  <div class="row clearfix">
    <div class="row clearfix">

      <div style="display: block"><%= paginate @departments %></div>

      <% @departments.each do |d| %>
          <div class="col-md-4 column">


            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">
                  <%= link_to d.name, d %>
                </h3>
              </div>
              <div class="panel-body">
                <%= d.description %>
              </div>
            </div>


          </div>
      <% end %>
    </div>

  </div>
</div>

app/views/departments/new.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="jumbotron">
        <h1>
          Add a Department!
        </h1>



        <%= form_for :department, url: school_departments_path, :html => {:class => "form-horizontal"} do |p| %>
            <% if @department.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@department.errors.count, "error") %> prohibited
                    this class from being saved:</h2>
                  <ul>
                    <% @department.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>

            <fieldset>

              <!-- Form Name -->
              <legend>Create Department</legend>

              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="prof_name">Department Name</label>

                <div class="col-md-4">
                  <%= p.text_field :name, class: "form-control input-md", placeholder: "Department Name" %>
                </div>

              </div>


              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="prof_department">Department Description</label>

                <div class="col-md-4">
                  <%= p.text_field :description, class: "form-control input-md", placeholder: "Description of the department" %>

                </div>
              </div>

              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="prof_department">Department Location</label>

                <div class="col-md-4">
                  <%= p.text_field :location, class: "form-control input-md", placeholder: "Location of the department" %>

                </div>
              </div>


              <!-- Button -->
              <div class="form-group">
                <label class="col-md-4 control-label" for="submit"></label>

                <div class="col-md-4">

                  <%= p.submit "Add Department", class: "btn btn-default" %>

                </div>
              </div>

            </fieldset>
        <% end %>


      </div>
    </div>
  </div>
  <div class="row clearfix">

  </div>
</div>

app/views/departments/show.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="leftInfoHolder">
      <div class="jumbotron">
        <h1>
          <%= @department.name %>
        </h1>


        <h3><%= @department.description %></h3>

        <h3><%= @department.location %></h3>


      </div>
    </div>
    <div class="rightInfoHolder">


    </div>

  </div>
  <div class="commentForm">


    <div class="panel panel-default">
      <div class="panel-body">

      </div>
    </div>

  </div>

  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="tabbable" id="tabs-385972">
        <ul class="nav nav-tabs nav-justified">
          <li class="active">
            <a href="#classlist" data-toggle="tab">Classes</a>
          </li>
          <li>
            <a href="#proflist" data-toggle="tab">Professors</a>
          </li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane active" id="classlist">

            <div class="row clearfix">

              <% @classlist.each do |cl| %>
                  <div class="col-md-4 column">


                    <div class="panel panel-default">
                      <div class="panel-heading">
                        <h3 class="panel-title">
                          <%= link_to cl.class_title, cl %>
                        </h3>
                      </div>
                      <div class="panel-body">
                        <%= cl.class_synopsis %>
                      </div>
                    </div>


                  </div>
              <% end %>


            </div>

            </p>
          </div>
          <div class="tab-pane" id="proflist">
            <div class="row clearfix">

              <% @proflist.each do |pl| %>
                  <div class="col-md-4 column">


                    <div class="panel panel-default">
                      <div class="panel-heading">
                        <h3 class="panel-title">
                          <%= link_to pl.first_name + " "+pl.last_name, pl %>
                        </h3>
                      </div>
                    </div>


                  </div>
              <% end %>


            </div>

          </div>
        </div>
      </div>
    </div>
  </div>


</div>
</div>

app/views/schools/create.html.erb
<h1>School#create</h1>
<p>Find me in app/views/school/create.html.erb</p>

app/views/schools/edit.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="jumbotron">
        <h1>
          Edit Information for <%= @school.name %>
        </h1>



        <%= form_for @school, url: school_path(@school), :html => {:class => "form-horizontal"} do |sc| %>
            <% if @school.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@school.errors.count, "error") %> prohibited
                    this class from being saved:</h2>
                  <ul>
                    <% @school.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>

            <fieldset>

              <!-- Form Name -->
              <legend>Edit School</legend>

              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="prof_name">School Name</label>

                <div class="col-md-4">
                  <%= sc.text_field :name, class: "form-control input-md", placeholder: "School Name" %>
                </div>

              </div>


              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="prof_department">Department Summary</label>

                <div class="col-md-4">
                  <%= sc.text_field :summary, class: "form-control input-md", placeholder: "Summary of the School" %>

                </div>
              </div>

              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="prof_department">School Address</label>

                <div class="col-md-4">
                  <%= sc.text_field :address, class: "form-control input-md", placeholder: "Address of the School" %>

                </div>
              </div>

              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="prof_department">School URL</label>

                <div class="col-md-4">
                  <%= sc.text_field :website, class: "form-control input-md", placeholder: "Website of the School" %>

                </div>
              </div>


              <!-- Button -->
              <div class="form-group">
                <label class="col-md-4 control-label" for="submit"></label>

                <div class="col-md-4">

                  <%= sc.submit "Save School", class: "btn btn-default" %>

                </div>
              </div>

            </fieldset>
        <% end %>



      </div>
    </div>
  </div>
</div>

app/views/schools/index.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="jumbotron">
        <h1>
          The Schools Will Go Here!
        </h1>

        <p>
          Blahdy Lorem Ipsum

        </p>

        <p>
          <%= link_to "Add New School", {:controller => "schools", action: "new"}, class: "btn btn-primary btn-large" %>
        </p>
      </div>
      <div class="row clearfix">

        <div style="display: block"><%= paginate @schools %></div>

        <% @schools.each do |sc| %>
            <div class="col-md-4 column">


              <div class="panel panel-default">
                <div class="panel-heading">
                  <h3 class="panel-title">
                    <%= link_to sc.name, sc %>
                  </h3>
                </div>
                <div class="panel-body">
                  <%= sc.summary %>
                  </br>
                </div>
              </div>


            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/schools/new.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="jumbotron">
        <h1>
          Add a School!
        </h1>



        <%= form_for :school, url: schools_path, :html => {:class => "form-horizontal"} do |sc| %>
            <% if @school.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@school.errors.count, "error") %> prohibited
                    this class from being saved:</h2>
                  <ul>
                    <% @school.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>

            <fieldset>

              <!-- Form Name -->
              <legend>Create School</legend>

              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="prof_name">School Name</label>

                <div class="col-md-4">
                  <%= sc.text_field :name, class: "form-control input-md", placeholder: "School Name" %>
                </div>

              </div>


              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="prof_department">School Summary</label>

                <div class="col-md-4">
                  <%= sc.text_field :summary, class: "form-control input-md", placeholder: "Summary of the School" %>

                </div>
              </div>

              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="prof_department">School Address</label>

                <div class="col-md-4">
                  <%= sc.text_field :address, class: "form-control input-md", placeholder: "Address of the School" %>

                </div>
              </div>

              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="prof_department">School URL</label>

                <div class="col-md-4">
                  <%= sc.text_field :website, class: "form-control input-md", placeholder: "Website of the School" %>

                </div>
              </div>


              <!-- Button -->
              <div class="form-group">
                <label class="col-md-4 control-label" for="submit"></label>

                <div class="col-md-4">

                  <%= sc.submit "Add School", class: "btn btn-default" %>

                </div>
              </div>

            </fieldset>
        <% end %>


      </div>
    </div>
  </div>
  <div class="row clearfix">

  </div>
</div>

app/views/schools/show.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="leftInfoHolder">
      <div class="jumbotron">
        <h1>
          <%= @school.name %>
        </h1>


        <h3><%= @school.summary %></h3>

        <h3><%= @school.address %></h3>


      </div>
    </div>
    <div class="rightInfoHolder">


    </div>

  </div>
  <div class="commentForm">


    <div class="panel panel-default">
      <div class="panel-body">

      </div>
    </div>

  </div>


</div>
</div>