config/routes.rb
Rails.application.routes.draw do


	resources :schools, path: nil do
		resources :departments
		resources :ru_classes
		resources :ru_professors
	end

	get 'about/index'

	root :to => "welcome#index"
	devise_for :users
	resources :users

	resources :departments

	resources :ru_professors do
		resources :prof_comments, shallow: true
	end
	resources :prof_comments

	resources :ru_classes do
		resources :class_comments, shallow: true
	end
	resources :class_comments

end

app/models/class_comment.rb
class ClassComment < ActiveRecord::Base
  belongs_to :ru_class
  belongs_to :user
end

app/models/department.rb
class Department < ActiveRecord::Base
  include FriendlyId
  friendly_id :name

  belongs_to :school

  validates :name, :description, presence: true

  has_many :ru_classes
  has_many :ru_professors
end

app/models/prof_class_map.rb
class ProfClassMap < ActiveRecord::Base
  belongs_to :ru_professor
  belongs_to :ru_class
end

app/models/prof_comment.rb
class ProfComment < ActiveRecord::Base
  belongs_to :ru_professor
  belongs_to :user
end

app/models/ru_class.rb
class RuClass < ActiveRecord::Base
  include FriendlyId
  friendly_id :class_title
  validates :class_title, :class_synopsis, presence: true, uniqueness: true

  has_many :class_comments
  has_many :prof_class_maps
  has_many :ru_professors, :through => :prof_class_maps

  belongs_to :department
end

app/models/ru_professor.rb
class RuProfessor < ActiveRecord::Base
  include FriendlyId
  friendly_id :last_name
  validates :first_name, :last_name, :email, presence: true

  has_many :prof_comments
  has_many :prof_class_maps
  has_many :ru_classes, :through => :prof_class_maps

  belongs_to :department
end

app/models/school.rb
class School < ActiveRecord::Base
  include FriendlyId
  friendly_id :name
  validates :name, :summary, :website, :address, presence: true

  has_many :departments

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :prof_comments
  has_many :class_comments
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/ru_classes_controller.rb
class RuClassesController < ApplicationController
  def index
    @classes = RuClass.order("class_title").page(params[:page]).per(10)
  end

  def show
    @class = RuClass.friendly.find(params[:id])
    @class_comment =ClassComment.new
    @comments = @class.class_comments.order('updated_at DESC')
    @professors = @class.ru_professors
    @department = @class.department

  end

  def create
    @class = RuClass.new(class_params)
    @class.department =Department.find(params[:ru_class][:department_select])

    if params[:ru_class][:ru_class_select].nil?
      puts "I'll probably put a pop-up here to see if they want to add one."
    else

      STDOUT.puts "IM INSIDE"
      prof_id=params[:ru_class][:ru_professor_select]
      prof_id.shift
      prof_id.each { |x|
        @profClassMap = ProfClassMap.new

        @prof=RuProfessor.find(x)

        @profClassMap.ru_class=@class
        @profClassMap.ru_professor=@prof
        @profClassMap.save

      }

    end


    if @class.save
      redirect_to @class
    else
      render 'new'
    end
  end

  def new
    @class = RuClass.new
  end

  def edit
    @class = RuClass.friendly.find(params[:id])
  end

  def update
    @class = RuClass.friendly.find(params[:id])
    if @class.update(class_params)
      redirect_to @class
    else
      redirect_to edit_ru_class_path
    end
  end
  private
  def class_params
    params.require(:ru_class).permit(:class_title, :class_code, :class_synopsis)
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def new
    @school = School.new
  end

  def create
    @school = School.new(school_params)


    if @school.save
      redirect_to @school
    else
      render 'new'
    end
  end

  def index
    @schools = School.order("name").page(params[:page]).per(10)
  end

  def show
    @school = School.friendly.find(params[:id])
  end

  def edit
    @school = School.friendly.find(params[:id])
  end

  def update
    @school = School.friendly.find(params[:id])
    if @school.update(school_params)
      redirect_to @school
    else
      redirect_to edit_school_path
    end
  end


  private
  def school_params
    params.require(:school).permit(:name, :summary, :website, :address, :phone)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @prof_comments = @user.prof_comments.all.page(params[:page]).per(10)
    @class_comments = @user.class_comments.all.page(params[:page]).per(10)


    #I want user to people to view the 'profiles' of the
    #
    #    unless @user == current_user
    #      redirect_to :back, :alert => "Access denied."
    #    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/class_comments_helper.rb
module ClassCommentsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/prof_comments_helper.rb
module ProfCommentsHelper
end

app/helpers/ru_classes_helper.rb
module RuClassesHelper
end

app/helpers/ru_professors_helper.rb
module RuProfessorsHelper
end

app/helpers/school_helper.rb
module SchoolHelper
end

app/views/about/index.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="jumbotron">
        <h1>
          About ReportCard
        </h1>

        <p>
          Let's make this the about page
        </p>
      </div>
    </div>
  </div>
  <div class="row clearfix">
    <p>Something is going to go here sooner or later.
    </p>
  </div>
</div>
</div>

app/views/ru_classes/create.html.erb
<h1>Classes#create</h1>
<p>Find me in app/views/classes/create.html.erb</p>

app/views/ru_classes/edit.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="jumbotron">
        <h1>
          Edit Information for <%= @class.class_title %>
        </h1>



        <%= form_for @class, url: ru_class_path(@class), :html => {:class => "form-horizontal"} do |cl| %>
            <% if @class.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@class.errors.count, "error") %> prohibited
                    this class from being saved:</h2>
                  <ul>
                    <% @class.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>

            <fieldset>

              <!-- Form Name -->
              <legend>Edit Class</legend>

              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="prof_name">Class Title</label>

                <div class="col-md-4">
                  <%= cl.text_field :class_title, class: "form-control input-md", placeholder: "Class Title" %>
                </div>

                <div class="col-md-4">
                  <%= cl.text_field :class_code, class: "form-control input-md", placeholder: "Class Code" %>
                </div>
              </div>


              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="prof_department">Class Synopsis</label>

                <div class="col-md-4">
                  <%= cl.text_field :class_synopsis, class: "form-control input-md", placeholder: "The synopsis of the class" %>

                </div>
              </div>
              <!-- Button -->
              <div class="form-group">
                <label class="col-md-4 control-label" for="submit"></label>

                <div class="col-md-4">

                  <%= cl.submit "Save Class", class: "btn btn-default" %>

                </div>
              </div>

            </fieldset>
        <% end %>


      </div>
    </div>
  </div>
  <div class="row clearfix">

  </div>
</div>

app/views/ru_classes/index.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="jumbotron">
        <h1>
          The Classes Will Go Here!
        </h1>

        <p>
          Blahdy Lorem Ipsum
        </p>

        <p>
          <%= link_to "Add New Class", {:controller => "ru_classes", action: "new"}, class: "btn btn-primary btn-large" %>
        </p>
      </div>
      <div class="row clearfix">

        <div style="display: block"><%= paginate @classes %></div>

        <% @classes.each do |c| %>
            <div class="col-md-4 column">


              <div class="panel panel-default">
                <div class="panel-heading">
                  <h3 class="panel-title">
                    <%= link_to c.class_title, c %>
                  </h3>
                </div>
                <div class="panel-body">
                  <%= c.class_synopsis %>
                </div>
              </div>


            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>`

app/views/ru_classes/new.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="jumbotron">
        <h1>
          Add a Class!
        </h1>



        <%= form_for :ru_class, url: ru_classes_path, :html => {:class => "form-horizontal"} do |p| %>
            <% if @class.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@class.errors.count, "error") %> prohibited
                    this class from being saved:</h2>
                  <ul>
                    <% @class.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>

            <fieldset>

              <!-- Form Name -->
              <legend>Create Class</legend>

              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="prof_name">Class Title</label>

                <div class="col-md-4">
                  <%= p.text_field :class_title, class: "form-control input-md", placeholder: "Class Title" %>
                </div>

                <div class="col-md-4">
                  <%= p.text_field :class_code, class: "form-control input-md", placeholder: "Class Code" %>
                </div>
              </div>


              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="prof_department">Class Synopsis</label>

                <div class="col-md-4">
                  <%= p.text_field :class_synopsis, class: "form-control input-md", placeholder: "The synopsis of the class" %>

                </div>
              </div>

              <!-- Text input-->
              <div class="form-group">
                <label class="col-md-4 control-label" for="prof_department">Choose Professors</label>

                <div class="col-md-4">
                  <%= p.select :ru_professor_select, options_for_select(RuProfessor.all.map { |r| [r.first_name + " "+r.last_name, r.id] }), {}, {:multiple => true, :class => "chosen-select"} %>
                </div>

              </div>

              <div class="form-group">
                <label class="col-md-4 control-label" for="prof_department">Choose Department</label>

                <div class="col-md-4">
                  <%= p.select :department_select, options_for_select(Department.all.map { |dpt| [dpt.name, dpt.id] }), {}, {:class => "chosen-select"} %>
                </div>
              </div>

              <!-- Button -->
              <div class="form-group">
                <label class="col-md-4 control-label" for="submit"></label>

                <div class="col-md-4">

                  <%= p.submit "Add Class", class: "btn btn-default" %>

                </div>
              </div>

            </fieldset>
        <% end %>


      </div>
    </div>
  </div>
  <div class="row clearfix">

  </div>
</div>

app/views/ru_classes/show.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="leftInfoHolder">
      <div class="jumbotron">
        <h1>
          <%= @class.class_title %>
        </h1>


        <h3><%= @class.class_code %></h3>

        <h3><%= @class.class_synopsis %></h3>

        <h4>Professors</h4>

        <% if @professors.size == 0 %>

            <p> <%= t('classNoProfessor') %> <%= render 'layouts/links/addProfessorLinker' %>

            </p>
        <% else %>

            <% @professors.each do |p| %>


                <%= link_to p.first_name + " " +p.last_name, p %> |

            <% end %>
        <% end %>

        <% if @department.nil? %>
            <p> <%= t('classNoDepartment') %> <%= render 'layouts/links/addDepartmentLinker' %>
            </p>
        <% else %>

            <h4>Department</h4>


            <%= link_to @department.name, @department %>


        <% end %>


      </div>
    </div>
    <div class="rightInfoHolder">
      <div class="jumbotron">
        <div class="ratingsbox"></div>
        <h2>Ratings</h2>

      </div>


    </div>

  </div>
  <div class="commentForm">


    <div class="panel panel-default">
      <div class="panel-body">
        <% if user_signed_in? %>
            <button type="button" class="btn btn-primary commentToggle" data-toggle="collapse" data-target="#commentFormHolder">
              Add Comment
            </button>

            <div id="commentFormHolder" class="collapse out">
              <%= render 'layouts/comments/add_class_comment' %>
            </div>
        <% else %>
            <%= render 'layouts/please_sign_in' %>
        <% end %>
      </div>
    </div>

  </div>

  <div class="row clearfix">

    <div id="commentContainer">
      <h2>Comments</h2>

      <% @comments.each do |c| %>
          <div class="col-md-4 column">


            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">
                  <%= link_to c.user.name, current_user %>
                </h3>
              </div>
              <div class="panel-body">
                <%= c.body %>
              </div>
            </div>


          </div>
      <% end %>
    </div>

  </div>
</div>

app/views/users/_user.html.erb
<td><%= user.name %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row-clearfix">
    <h3>Users</h3>

    <div class="column">
      <table class="table">
        <tbody>
        <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="jumbotron">
        <h1>
          <%= @user.name %>
        </h1>

        <p>
          This is going to be the main profile page for a user. Something will go here sooner or later. </p>

      </div>
    </div>
  </div>
  <div class="row clearfix">
    <div class="col-md-6 column profCommentHolder">
      <%= render 'layouts/comments/user_profcomment_listing' %>
    </div>
    <div class="col-md-6 column classCommentHolder">
      <%= render 'layouts/comments/user_classcomment_listing' %>
    </div>
  </div>
</div>