config/routes.rb
Rails.application.routes.draw do


	resources :schools, path: nil do
		resources :departments
		resources :ru_classes
		resources :ru_professors
	end

	get 'about/index'

	root :to => "welcome#index"
	devise_for :users
	resources :users

	resources :departments

	resources :ru_professors do
		resources :prof_comments, shallow: true
	end
	resources :prof_comments

	resources :ru_classes do
		resources :class_comments, shallow: true
	end
	resources :class_comments

end

app/models/class_comment.rb
class ClassComment < ActiveRecord::Base
  belongs_to :ru_class
  belongs_to :user
end

app/models/department.rb
class Department < ActiveRecord::Base
  include FriendlyId
  friendly_id :name

  belongs_to :school

  validates :name, :description, presence: true

  has_many :ru_classes
  has_many :ru_professors
end

app/models/prof_class_map.rb
class ProfClassMap < ActiveRecord::Base
  belongs_to :ru_professor
  belongs_to :ru_class
end

app/models/prof_comment.rb
class ProfComment < ActiveRecord::Base
  belongs_to :ru_professor
  belongs_to :user
end

app/models/ru_class.rb
class RuClass < ActiveRecord::Base
  include FriendlyId
  friendly_id :class_title
  validates :class_title, :class_synopsis, presence: true, uniqueness: true

  has_many :class_comments
  has_many :prof_class_maps
  has_many :ru_professors, :through => :prof_class_maps

  belongs_to :department
end

app/models/ru_professor.rb
class RuProfessor < ActiveRecord::Base
  include FriendlyId
  friendly_id :last_name
  validates :first_name, :last_name, :email, presence: true

  has_many :prof_comments
  has_many :prof_class_maps
  has_many :ru_classes, :through => :prof_class_maps

  belongs_to :department
end

app/models/school.rb
class School < ActiveRecord::Base
  include FriendlyId
  friendly_id :name
  validates :name, :summary, :website, :address, presence: true

  has_many :departments

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :prof_comments
  has_many :class_comments
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def new
    @school = School.new
  end

  def create
    @school = School.new(school_params)


    if @school.save
      redirect_to @school
    else
      render 'new'
    end
  end

  def index
    @schools = School.order("name").page(params[:page]).per(10)
  end

  def show
    @school = School.friendly.find(params[:id])
  end

  def edit
    @school = School.friendly.find(params[:id])
  end

  def update
    @school = School.friendly.find(params[:id])
    if @school.update(school_params)
      redirect_to @school
    else
      redirect_to edit_school_path
    end
  end


  private
  def school_params
    params.require(:school).permit(:name, :summary, :website, :address, :phone)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @prof_comments = @user.prof_comments.all.page(params[:page]).per(10)
    @class_comments = @user.class_comments.all.page(params[:page]).per(10)


    #I want user to people to view the 'profiles' of the
    #
    #    unless @user == current_user
    #      redirect_to :back, :alert => "Access denied."
    #    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/class_comments_helper.rb
module ClassCommentsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/prof_comments_helper.rb
module ProfCommentsHelper
end

app/helpers/ru_classes_helper.rb
module RuClassesHelper
end

app/helpers/ru_professors_helper.rb
module RuProfessorsHelper
end

app/helpers/school_helper.rb
module SchoolHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t('institutionName')+' '+ t('navHeader'), root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-left">
        <%# add navigation links to this file %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Professors<strong class="caret"></strong></a>
          <ul class="dropdown-menu">
            <li>
              <a href="<%= ru_professors_path %>">View All Professors</a>
            </li>
            <li>
              <a href="<%= new_ru_professor_path %>">Add Professor</a>
            </li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Classes &
            Departments<strong class="caret"></strong></a>
          <ul class="dropdown-menu">
            <li>
              <a href="<%= ru_classes_path %>">View All Classes</a>
            </li>
            <li>
              <a href="<%= new_ru_class_path %>">Add Class</a>
            </li>
            <li class="divider"></li>
            <li><%= link_to 'View Departments', departments_path %></li>
            <li><%= link_to 'Add Department', new_department_path %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%# add navigation links to this file %>
        <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %>
                <strong class="caret"></strong></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'View Profile', edit_user_registration_path %></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, :method => 'delete' %></li>
                <li class="divider"></li>
                <li><%= link_to 'About ReportCard', about_index_path %></li>
              </ul>
            </li>

        <% else %>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <li><%= link_to 'About ReportCard', about_index_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_please_sign_in.html.erb
<%= link_to "Please Sign In To Comment", new_user_session_path, :class => "btn btn-danger" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : t('title') %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Report Card Io" %>">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <%= render 'layouts/navigation' %>
</header>
<main role="main">
  <%= render 'layouts/messages' %>
  <%= yield %>
</main>
</body>
</html>

app/views/layouts/links/_addClassLinker.html.erb
Do you want to <%= link_to t('add'), {:controller => 'ru_classes', action: 'new'} %>

app/views/layouts/links/_addDepartmentLinker.html.erb
Do you want to <%= link_to t('add'), {:controller => "departments", action: "new"} %>

app/views/layouts/links/_addProfessorLinker.html.erb
Do you want to <%= link_to t('add'), {:controller => 'ru_professors', action: 'new'} %>